### ISSUE TITLE
Frame Jumping with Run-Ahead to reduce latency

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-bsnes-libretro#30]
Activating the latency reduction leads to a weird jumping of frames.
Sometimes frames are dropped sometimes completely different frames are added.
Best examples are Donkey Kong Country or Super Mario World.

**Comment by Papermanzero** [comment]
I have to add another issue with bsnes-mercury core: The input is not working correctly with Run-Ahead. The button cannot be hold anymore (recognized as several presses)

**Comment by Papermanzero** [comment]
The strange thing: the mednafen version of bsnes is working withiut issue. However there are some graphic display bugs

**Comment by hizzlekizzle** [comment]
bsnes c++98 (a snapshot from around bsnes v085) seems to work okay with it, too.

**Comment by Papermanzero** [comment]
I close the issue. I recognized that I rised the issue for the wrong core.
