### ISSUE TITLE
Any plans to migrate to snes_faust?

### ISSUE THREAD

**Issue by keithbowes** [libretro/beetle-bsnes-libretro#41]
Mednafen has a newer, faster module called snes_faust, which is actually under active development.  It would be nice if there were a libretro core for it, instead of this slow, unmaintained bsnes-based one.

**Comment by hizzlekizzle** [comment]
I would love that, actually.

Someone let me try a preliminary libretro-ization of snes_faust a few months ago and it was really great. I figured they were pretty close to releasing it but I haven't heard anything from them since, so fingers crossed that they release it soon.

**Comment by keithbowes** [comment]
I just noticed the supafaust repository.  I'll close this issue, as an snes_faust core is now available.
